use serde::Serialize;

use crate::detect::HandlerKind;

#[derive(Debug, Clone, Copy, Serialize, PartialEq, Eq)]
pub struct Capabilities {
    pub preview: bool,
    pub info: bool,
    pub schema: bool,
    pub find: bool,
    pub stats: bool,
    pub query: bool,
    pub diff: bool,
    pub text: bool,
    pub metadata: bool,
    pub hash: bool,
    pub duplicates: bool,
    pub encoding: bool,
    pub follow: bool,
    pub watch: bool,
    pub virtual_path: bool,
}

impl Capabilities {
    pub fn for_kind(kind: HandlerKind) -> Self {
        let mut c = match kind {
            HandlerKind::Markdown => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: true,
                query: false,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Image => Self {
                preview: true,
                info: true,
                schema: false,
                find: false,
                stats: true,
                query: false,
                diff: true,
                text: false,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Data => Self {
                preview: true,
                info: true,
                schema: true,
                find: true,
                stats: true,
                query: true,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Pdf => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: true,
                query: false,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Archive => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: true,
                query: false,
                diff: false,
                text: false,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Code => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: true,
                query: false,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Spreadsheet => Self {
                preview: true,
                info: true,
                schema: true,
                find: true,
                stats: true,
                query: false,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Document | HandlerKind::Ebook | HandlerKind::Email => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: true,
                query: false,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Presentation | HandlerKind::Notebook => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: false,
                query: false,
                diff: false,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::LegacyOffice => Self {
                preview: true,
                info: true,
                schema: false,
                find: false,
                stats: false,
                query: false,
                diff: false,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Directory => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: true,
                query: false,
                diff: false,
                text: false,
                metadata: true,
                hash: true,
                duplicates: true,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Media => Self {
                preview: true,
                info: true,
                schema: false,
                find: false,
                stats: true,
                query: false,
                diff: true,
                text: false,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Font => Self {
                preview: true,
                info: true,
                schema: false,
                find: false,
                stats: false,
                query: false,
                diff: false,
                text: false,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Database => Self {
                preview: true,
                info: true,
                schema: true,
                find: true,
                stats: true,
                query: true,
                diff: true,
                text: false,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Plist => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: false,
                query: false,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
            HandlerKind::Fallback => Self {
                preview: true,
                info: true,
                schema: false,
                find: true,
                stats: true,
                query: false,
                diff: true,
                text: true,
                metadata: true,
                hash: true,
                duplicates: false,
                encoding: false,
                follow: false,
                watch: false,
                virtual_path: false,
            },
        };
        apply_kind_extras(&mut c, kind);
        c
    }

    pub fn labels(&self) -> Vec<(&'static str, bool)> {
        vec![
            ("preview", self.preview),
            ("info", self.info),
            ("schema", self.schema),
            ("find", self.find),
            ("stats", self.stats),
            ("query", self.query),
            ("diff", self.diff),
            ("text", self.text),
            ("metadata", self.metadata),
            ("hash", self.hash),
            ("duplicates", self.duplicates),
            ("encoding", self.encoding),
            ("follow", self.follow),
            ("watch", self.watch),
            ("virtual_path", self.virtual_path),
        ]
    }
}

fn apply_kind_extras(caps: &mut Capabilities, kind: HandlerKind) {
    caps.encoding = caps.text || matches!(kind, HandlerKind::Data | HandlerKind::Plist);
    caps.follow = caps.encoding;
    caps.watch = caps.preview;
    caps.virtual_path = kind == HandlerKind::Archive;
}
